### ISSUE TITLE
head bug

### ISSUE THREAD

**Issue by mspoulsen** [TylorS167/167#13]
````javascript
import { head } from '167'

console.log(head([0])) // returns [] expected 0

**Comment by Frikki** [comment]
Correction: it returns `undefined`, because in `return list[0] || void 0`, `list[0]` evaluates to _falsy_ and, thus, returns `void 0`. See https://github.com/TylorS167/167/blob/master/src/list/head/head.ts#L11

I don't see any reason to make this check (first of all because 0 is _falsy_), and returning `list[0]` where `list = []` returns `undefined` in any case.

Thus, L11 could simply be `return list[0]`.
